all: clean test
	@echo "*** COMPLETED in test **"

clean:
	cd ./master_statechg_test;make clean
	@echo "*** CLEAN COMPLETED in test ***"

test:
	cd ./master_statechg_test;make test
	@echo "*** TEST COMPLETED in test ***"