#!/bin/bash
TSTAMP=$( date )
curl -H "content-Type: application/json" -X POST -d "{\"State\":\"TEST\", \"InstName\": \"MainTestInstance\", \"Count\": 0, \"Tstamp\": \"$TSTAMP\"}" http://localhost:8080/status/
