all: clean test
	@echo "*** COMPLETED in tools **"

clean:
	@echo "*** CLEAN COMPLETED in tools ***"

test:
	@echo "*** TEST COMPLETED in tools ***"

install:
	cp *.sh /usr/local/accord/testtools/
	@echo "*** INSTALL COMPLETED in tools ***"
